import { useState, useEffect } from 'react'
import { fetchHistory, deleteExplanation } from '../hooks/useHistory'
import jsPDF from 'jspdf'

const MODE_EMOJIS = {
  cinematic: '🎬',
  cooking: '🍳',
  roast: '🔥',
  grandma: '👴',
  medieval: '⚔️',
  horoscope: '🔮',
}

function HistoryPanel({ userId, onClose }) {
  const [history, setHistory] = useState([])
  const [loading, setLoading] = useState(true)
  const [expanded, setExpanded] = useState(null)
  const [selected, setSelected] = useState([])

  useEffect(() => {
    fetchHistory(userId).then(data => {
      setHistory(data)
      setLoading(false)
    })
  }, [userId])

  const handleDelete = async (id) => {
    await deleteExplanation(id)
    setHistory(history.filter(item => item.id !== id))
    setSelected(selected.filter(s => s !== id))
  }

  const toggleSelect = (id) => {
    setSelected(prev =>
      prev.includes(id) ? prev.filter(s => s !== id) : [...prev, id]
    )
  }

  const formatDate = (timestamp) => {
    return new Date(timestamp).toLocaleString('en-IN', {
      day: 'numeric',
      month: 'short',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const handleExportSelected = () => {
    const items = history.filter(item => selected.includes(item.id))
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    const maxWidth = pageWidth - margin * 2
    let y = 20
    let isFirstPage = true

    items.forEach((item, index) => {
      if (!isFirstPage) {
        doc.addPage()
        y = 20
      }

      // Header on first page only
      if (isFirstPage) {
        doc.setFillColor(10, 10, 10)
        doc.rect(0, 0, pageWidth, 40, 'F')
        doc.setTextColor(0, 255, 159)
        doc.setFontSize(18)
        doc.setFont('courier', 'bold')
        doc.text('PARSELY', margin, 25)
        doc.setTextColor(136, 136, 136)
        doc.setFontSize(9)
        doc.setFont('courier', 'normal')
        doc.text('your code. every personality.', margin, 34)
        y = 55
        isFirstPage = false
      }

      // Entry number
      doc.setTextColor(0, 255, 159)
      doc.setFontSize(10)
      doc.setFont('courier', 'bold')
      doc.text(`[${index + 1}] MODE: ${item.mode.toUpperCase()}`, margin, y)
      y += 8

      doc.setTextColor(136, 136, 136)
      doc.setFontSize(9)
      doc.setFont('courier', 'normal')
      doc.text(`Generated: ${formatDate(item.created_at)}`, margin, y)
      y += 12

      // Divider
      doc.setDrawColor(51, 51, 51)
      doc.line(margin, y, pageWidth - margin, y)
      y += 8

      // Code
      doc.setTextColor(0, 255, 159)
      doc.setFontSize(9)
      doc.setFont('courier', 'bold')
      doc.text('// CODE', margin, y)
      y += 7

      const codeLines = doc.splitTextToSize(item.code, maxWidth - 10)
      const codeBlockHeight = codeLines.length * 5 + 10
      doc.setFillColor(240,240,240)
      doc.rect(margin, y - 4, maxWidth, codeBlockHeight, 'F')
      doc.setTextColor(30,30,30)
      doc.setFontSize(8)
      doc.setFont('courier', 'normal')
      doc.text(codeLines, margin + 5, y + 2)
      y += codeBlockHeight + 8

      // Output
      doc.setTextColor(0, 255, 159)
      doc.setFontSize(9)
      doc.setFont('courier', 'bold')
      doc.text('// OUTPUT', margin, y)
      y += 7

      doc.setTextColor(0,0,0)
      doc.setFontSize(9)
      doc.setFont('courier', 'normal')
      const outputLines = doc.splitTextToSize(item.output, maxWidth)
      outputLines.forEach(line => {
        if (y > 270) {
          doc.addPage()
          y = 20
        }
        doc.text(line, margin, y)
        y += 6
      })

      y += 10
    })

    // Footer
    doc.setTextColor(51, 51, 51)
    doc.setFontSize(8)
    doc.text('Generated by Parsely 🌿', margin, 285)

    doc.save(`parsely-history-${Date.now()}.pdf`)
  }

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      right: 0,
      width: '400px',
      height: '100vh',
      backgroundColor: '#0f0f0f',
      borderLeft: '2px solid #00ff9f',
      overflowY: 'auto',
      zIndex: 1000,
      padding: '20px',
      boxSizing: 'border-box',
    }}>

      {/* Header */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '20px',
      }}>
        <p style={{ fontFamily: "'Press Start 2P'", fontSize: '10px', color: '#00ff9f', margin: 0 }}>
          // HISTORY
        </p>
        <button
          onClick={onClose}
          style={{
            backgroundColor: 'transparent',
            color: '#ff4444',
            border: '2px solid #ff4444',
            fontFamily: "'Press Start 2P'",
            fontSize: '8px',
            padding: '6px 10px',
            cursor: 'pointer',
            boxShadow: '2px 2px 0px #880000',
          }}
        >
          CLOSE
        </button>
      </div>

      {/* Divider */}
      <p style={{ color: '#555555', fontFamily: 'Courier New', marginBottom: '16px' }}>
        =-=-=-=-=-=-=-=-=-=-=-=-=
      </p>

      {/* Export selected button */}
      {selected.length > 0 && (
        <button
          onClick={handleExportSelected}
          style={{
            backgroundColor: '#00eaff',
            color: '#0a0a0a',
            fontFamily: "'Press Start 2P'",
            fontSize: '8px',
            padding: '10px 16px',
            border: 'none',
            cursor: 'pointer',
            boxShadow: '3px 3px 0px #007a8a',
            width: '100%',
            marginBottom: '16px',
          }}
          onMouseEnter={e => e.currentTarget.style.transform = 'translateY(2px)'}
          onMouseLeave={e => e.currentTarget.style.transform = 'translateY(0)'}
        >
          EXPORT {selected.length} SELECTED AS PDF ▼
        </button>
      )}

      {/* Content */}
      {loading ? (
        <p style={{ fontFamily: "'Press Start 2P'", fontSize: '8px', color: '#555555' }}>
          LOADING...
        </p>
      ) : history.length === 0 ? (
        <p style={{ fontFamily: 'Courier New', fontSize: '13px', color: '#555555' }}>
          // no history yet. generate something!
        </p>
      ) : (
        history.map(item => (
          <div
            key={item.id}
            style={{
              backgroundColor: '#111111',
              border: `2px solid ${selected.includes(item.id) ? '#00eaff' : '#222222'}`,
              padding: '14px',
              marginBottom: '12px',
              boxShadow: selected.includes(item.id) ? '3px 3px 0px #007a8a' : '3px 3px 0px #1a1a1a',
            }}
          >

            {/* Card header */}
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'flex-start',
              marginBottom: '8px',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                {/* Checkbox */}
                <div
                  onClick={() => toggleSelect(item.id)}
                  style={{
                    width: '16px',
                    height: '16px',
                    border: `2px solid ${selected.includes(item.id) ? '#00eaff' : '#555555'}`,
                    backgroundColor: selected.includes(item.id) ? '#00eaff' : 'transparent',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                  }}
                >
                  {selected.includes(item.id) && (
                    <span style={{ color: '#0a0a0a', fontSize: '10px', fontWeight: 'bold' }}>✓</span>
                  )}
                </div>
                <span style={{ fontSize: '18px' }}>{MODE_EMOJIS[item.mode]}</span>
                <span style={{
                  fontFamily: "'Press Start 2P'",
                  fontSize: '8px',
                  color: '#00ff9f',
                }}>
                  {item.mode.toUpperCase()}
                </span>
              </div>
              <button
                onClick={() => handleDelete(item.id)}
                style={{
                  backgroundColor: 'transparent',
                  color: '#ff4444',
                  border: 'none',
                  fontFamily: 'Courier New',
                  fontSize: '12px',
                  cursor: 'pointer',
                  padding: '2px 6px',
                }}
              >
                ✕
              </button>
            </div>

            {/* Timestamp */}
            <p style={{
              fontFamily: 'Courier New',
              fontSize: '11px',
              color: '#555555',
              margin: '0 0 8px 0',
            }}>
              {formatDate(item.created_at)}
            </p>

            {/* Code preview */}
            <p style={{
              fontFamily: 'Courier New',
              fontSize: '11px',
              color: '#888888',
              margin: '0 0 10px 0',
              backgroundColor: '#0a0a0a',
              padding: '8px',
              borderLeft: '2px solid #333333',
              whiteSpace: 'nowrap',
              overflow: 'hidden',
              textOverflow: 'ellipsis',
            }}>
              {item.code.slice(0, 80)}...
            </p>

            {/* Expand button */}
            <button
              onClick={() => setExpanded(expanded === item.id ? null : item.id)}
              style={{
                backgroundColor: 'transparent',
                color: '#888888',
                border: '2px solid #333333',
                fontFamily: "'Press Start 2P'",
                fontSize: '7px',
                padding: '6px 10px',
                cursor: 'pointer',
                width: '100%',
                marginBottom: expanded === item.id ? '10px' : '0',
              }}
            >
              {expanded === item.id ? 'HIDE ▲' : 'VIEW OUTPUT ▼'}
            </button>

            {/* Expanded content */}
            {expanded === item.id && (
              <div style={{ borderTop: '1px solid #222222', paddingTop: '10px' }}>
                <p style={{
                  fontFamily: "'Press Start 2P'",
                  fontSize: '7px',
                  color: '#555555',
                  margin: '0 0 6px 0',
                }}>
                  // CODE
                </p>
                <pre style={{
                  fontFamily: 'Courier New',
                  fontSize: '11px',
                  color: '#888888',
                  backgroundColor: '#0a0a0a',
                  padding: '10px',
                  borderLeft: '2px solid #333333',
                  margin: '0 0 12px 0',
                  whiteSpace: 'pre-wrap',
                  wordBreak: 'break-word',
                  maxHeight: '150px',
                  overflowY: 'auto',
                }}>
                  {item.code}
                </pre>
                <p style={{
                  fontFamily: "'Press Start 2P'",
                  fontSize: '7px',
                  color: '#555555',
                  margin: '0 0 6px 0',
                }}>
                  // OUTPUT
                </p>
                <p style={{
                  fontFamily: 'Courier New',
                  fontSize: '12px',
                  color: '#cccccc',
                  lineHeight: '1.7',
                  margin: 0,
                  whiteSpace: 'pre-wrap',
                }}>
                  {item.output}
                </p>
              </div>
            )}

          </div>
        ))
      )}
    </div>
  )
}

export default HistoryPanel