import { useState } from 'react'
import jsPDF from 'jspdf'

function OutputPanel({ output, loading, mode, code }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    navigator.clipboard.writeText(output)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleExportPDF = () => {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    const maxWidth = pageWidth - margin * 2
    let y = 20

    // Header
    doc.setFillColor(10, 10, 10)
    doc.rect(0, 0, pageWidth, 40, 'F')
    doc.setTextColor(0, 255, 159)
    doc.setFontSize(18)
    doc.setFont('courier', 'bold')
    doc.text('PARSELY', margin, 25)

    doc.setTextColor(136, 136, 136)
    doc.setFontSize(9)
    doc.setFont('courier', 'normal')
    doc.text('your code. every personality.', margin, 34)

    y = 55

    // Mode + timestamp
    doc.setTextColor(0, 255, 159)
    doc.setFontSize(10)
    doc.setFont('courier', 'bold')
    doc.text(`MODE: ${mode.toUpperCase()}`, margin, y)
    y += 8

    doc.setTextColor(80,80,80)
    doc.setFontSize(9)
    doc.setFont('courier', 'normal')
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y)
    y += 14

    // Divider
    doc.setDrawColor(51, 51, 51)
    doc.line(margin, y, pageWidth - margin, y)
    y += 10

    // Code section
    doc.setTextColor(0, 255, 159)
    doc.setFontSize(9)
    doc.setFont('courier', 'bold')
    doc.text('// CODE', margin, y)
    y += 8

    const codeLines = doc.splitTextToSize(code, maxWidth - 10)
    const codeBlockHeight = codeLines.length * 5 + 10
    doc.setFillColor(240, 240, 240)
    doc.rect(margin, y - 4, maxWidth, codeBlockHeight, 'F')
    doc.setTextColor(30,30,30)
    doc.setFontSize(8)
    doc.setFont('courier', 'normal')
    doc.text(codeLines, margin + 5, y + 2)
    y += codeBlockHeight + 10

    // Divider
    doc.setDrawColor(51, 51, 51)
    doc.line(margin, y, pageWidth - margin, y)
    y += 10

    // Output section
    doc.setTextColor(0, 255, 159)
    doc.setFontSize(9)
    doc.setFont('courier', 'bold')
    doc.text('// OUTPUT', margin, y)
    y += 8

    doc.setTextColor(0,0,0)
    doc.setFontSize(9)
    doc.setFont('courier', 'normal')
    const outputLines = doc.splitTextToSize(output, maxWidth)

    outputLines.forEach(line => {
      if (y > 270) {
        doc.addPage()
        y = 20
      }
      doc.text(line, margin, y)
      y += 6
    })

    // Footer
    doc.setTextColor(51, 51, 51)
    doc.setFontSize(8)
    doc.text('Generated by Parsely', margin, 285)

    doc.save(`parsely-${mode}-${Date.now()}.pdf`)
  }

  return (
    <div>
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '12px',
      }}>
        <p style={{
          fontFamily: "'Press Start 2P'",
          fontSize: '10px',
          color: '#00ff9f',
          margin: 0,
        }}>
          // OUTPUT
        </p>
        {output && (
          <div style={{ display: 'flex', gap: '8px' }}>
            <button
              onClick={handleCopy}
              style={{
                backgroundColor: 'transparent',
                color: copied ? '#00ff9f' : '#888888',
                fontFamily: "'Press Start 2P'",
                fontSize: '8px',
                padding: '6px 12px',
                border: `2px solid ${copied ? '#00ff9f' : '#555555'}`,
                cursor: 'pointer',
                boxShadow: '2px 2px 0px #222222',
              }}
            >
              {copied ? 'COPIED!' : 'COPY'}
            </button>
            <button
              onClick={handleExportPDF}
              style={{
                backgroundColor: 'transparent',
                color: '#00eaff',
                fontFamily: "'Press Start 2P'",
                fontSize: '8px',
                padding: '6px 12px',
                border: '2px solid #00eaff',
                cursor: 'pointer',
                boxShadow: '2px 2px 0px #007a8a',
              }}
              onMouseEnter={e => e.currentTarget.style.transform = 'translateY(1px)'}
              onMouseLeave={e => e.currentTarget.style.transform = 'translateY(0)'}
            >
              PDF
            </button>
          </div>
        )}
      </div>
      <div style={{
        backgroundColor: '#111111',
        border: '2px solid #555555',
        padding: '16px',
        minHeight: '150px',
        fontFamily: 'Courier New',
        fontSize: '13px',
        color: '#cccccc',
        lineHeight: '1.8',
        whiteSpace: 'pre-wrap',
      }}>
        {loading ? (
          <p style={{
            color: '#00ff9f',
            fontFamily: "'Press Start 2P'",
            fontSize: '10px',
          }}>
            PARSING... ▌
          </p>
        ) : output ? (
          output
        ) : (
          <p style={{ color: '#555555', fontFamily: 'Courier New' }}>
            // your explanation will appear here...
          </p>
        )}
      </div>
    </div>
  )
}

export default OutputPanel